v3io/v3io-go

pkg/dataplane/http/session.go
Because web API rejects requests with both headers with 400 Bad Request:
```
{
"ErrorCode": -369098782,
"ErrorMessage": "Invalid web-API request: the request includes headers for both basic-HTTP and access-key (session-key) authentication"
}
```
=> Leave authentication token empty when access key is provided.

pkg/dataplane/http/context.go, pkg/errors/errors.go
Error before:
```
Failed DELETE with status 409 (409 response code)
```
Error after: 
```
HTTP/1.1 409 Conflict
Date: Thu, 06 Jun 2019 08:23:10 GMT
Content-Type: application/json
Content-Length: 61
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains
{"ErrorCode": -39,"ErrorMessage": "Directory not empty"}
```
=> Include full HTTP response in error.

Makefile, README.md, go.mod, go.sum, hack/lint.sh, pkg/controlplane/http/session.go, pkg/controlplane/test/controlplane_test.go, pkg/dataplane/http/context.go, pkg/dataplane/http/headers.go, pkg/dataplane/requestresponse.go, pkg/dataplane/schemas/clean, pkg/dataplane/test/sync_test.go, pkg/dataplane/types.go
=> Make V3IO-GO great again

pkg/dataplane/http/container.go, pkg/dataplane/http/context.go, pkg/dataplane/http/session.go, pkg/dataplane/test/test.go, pkg/dataplane/types.go
And use Client instead of HostClient in order to support specifying the target URL at request time (as opposed to client creation time).
=> IG-13067: Factor http client out of context so that it can be reused independently of it.

pkg/dataplane/http/context.go
Because:
* It requires reallocating the full body as a string, even when the log level is less verbose than debug.
* It often blows up the log size when debug is on.
=> Delete logging of body in debug mode. Log Content-Length instead.

pkg/dataplane/container.go, pkg/dataplane/http/container.go, pkg/dataplane/http/context.go, pkg/dataplane/test/sync_test.go, pkg/dataplane/types.go
Create an output for update and put item containing `mtime`.
=> Add Update/Put item output

pkg/dataplane/http/context.go, pkg/dataplane/streamconsumergroup/claim.go, pkg/dataplane/streamconsumergroup/member.go, pkg/dataplane/streamconsumergroup/sequencenumberhandler.go, pkg/dataplane/streamconsumergroup/session.go, pkg/dataplane/streamconsumergroup/statehandler.go, pkg/dataplane/streamconsumergroup/streamconsumergroup.go, pkg/dataplane/streamconsumergroup/types.go, pkg/dataplane/test/streamconsumergroup_test.go
1. StreamConsumerGroup is now a stateless object with which all access to the persistency is performed (can be used to retreive information about a consumer group)
2. All "stateful" components of the StreamConsumerGroup moved to the "Member" - a new object introduced that holds the sequence number handler, state handler, etc
=> Refactored consumer group interface

pkg/dataplane/http/context.go
Under a certain error condition, the code paniced due to accessing an unused variable.
=> Dont panic incorrect due to error

pkg/dataplane/container.go, pkg/dataplane/http/container.go, pkg/dataplane/http/context.go, pkg/dataplane/http/headers.go, pkg/dataplane/types.go
Signed-off-by: Eyal Salomon <eyals@iguazio.com>
=> v3io-go: added OosRun interface

pkg/dataplane/itemscursor.go
`currentError` was not set anywhere in `itemscursor`
=> Update itemcursor current error when GetItemsSync returns an error

Makefile, pkg/dataplane/http/context.go, pkg/dataplane/test/sync_test.go, pkg/dataplane/types.go, pkg/errors/errors.go
Include http response in error struct
This is needed since response may include `NextMarker` field which is required to skip items which caused an error
=> Include response in err struct

Makefile, pkg/dataplane/streamconsumergroup/claim.go, pkg/dataplane/streamconsumergroup/config.go, pkg/dataplane/test/sync_test.go
When starting to consume from a stream, we fetch some stream metadata from v3io server. when failing doing so, the entire process of consuming from a stream being left in bad shape.
To  provide resiliency and avoid failures in case of transient network errors, it is desired to retry for a while.
=> Retry getting shard in case of network instability

pkg/dataplane/streamconsumergroup/streamconsumergroup.go
Upon state file creation, multiple replicas will try to create the file. we want to ensure only one succeed
=> Consumer group - fix race condition on creating state file

Makefile, pkg/controlplane/test/controlplane_test.go
Fixing existing breakages (`make test-controlplane` now passes):
- Typo in some logging calls
- Deprecated create container by ID logic (no longer supported as of 3.0)
- Added verbose flag to makefile so we can see debug logs
=> Tests - Fix controlplane tests

.github/workflows/ci.yaml, Makefile, hack/script/generate_access_key.sh, hack/test/docker/Dockerfile, pkg/dataplane/test/sync_test.go
- Stabilizing CI - Disabling (Commenting out) failing dataplane tests -  `TestIncludeResponseInError `, `TestSetDirsAttrs`
- `Makefile` - new entries for system test and dfor dataplane tests (simple) - the reason for this is that even with the above there are data races detected, hence CI can't pass today with `-race` flag
- Added docker file and dockerized make target for jemkins CI - usage: `make test-system-in-docker` with the needed env vars populated (see intended usage)
- Adding helper script `generate_access_key.sh` to generate an access key:
- Run with:
```bash
$ ./hack/script/generate_access_key.sh
[output]
...
...
Creating Data Access Key
V3IO_DATAPLANE_ACCESS_KEY=e035353c-b277-4854-93fe-59a1a1ef2dd5
```
- OUTPUT: the last line of the script can be parsed and used by CI to …
=> CI preparations

go.sum, pkg/dataplane/streamconsumergroup/claim.go, pkg/dataplane/streamconsumergroup/member.go, pkg/dataplane/streamconsumergroup/session.go, pkg/dataplane/streamconsumergroup/statehandler.go, pkg/dataplane/streamconsumergroup/statehandler_test.go, pkg/dataplane/streamconsumergroup/streamconsumergroup.go, pkg/dataplane/streamconsumergroup/types.go, pkg/dataplane/test/streamconsumergroup_test.go, pkg/dataplane/test/test.go
It is observed that members can steal shards from other members due to other members being stale falsely.
We introduce a Shard Retention Mechanism:
If a certain replica is assigned to a shard group, and comes back after an error - try to grab the same shard group (the original one).
If it succeeds - no problem.
If it fails (due to another replica stealing the shard group - can only happen during shard assignment) - the replica will kill itself.
Requirement: https://jira.iguazeng.com/browse/IG-20025
Nuclio PR: https://github.com/nuclio/nuclio/pull/2484
=> Stream Consumer Group - Shard retention mechanism

pkg/dataplane/streamconsumergroup/claim.go, pkg/dataplane/types.go
Add the arrival time so consumer will be able to refer to the actual time of the event arriving on the stream.
Resolves one part of https://jira.iguazeng.com/browse/NUC-111
=> [Claim] Add arrival time to Stream Record batch

pkg/dataplane/streamconsumergroup/statehandler.go, pkg/dataplane/streamconsumergroup/streamconsumergroup.go
Fixed a few error checks that were wrongly set to `errors.Is` instead of `!errors.Is` in #144 .
Resolves https://jira.iguazeng.com/browse/NUC-117
=> [StreamConsumerGroup] Fix error checks

pkg/common/helper.go, pkg/dataplane/streamconsumergroup/claim.go, pkg/dataplane/streamconsumergroup/streamconsumergroup.go, pkg/dataplane/test/streamconsumergroup_test.go
Jira - https://iguazio.atlassian.net/browse/NUC-340
=> Wait forever for fatal errors

pkg/common/helper.go, pkg/dataplane/streamconsumergroup/claim.go
Changed as it turned out not to be external dependency issue, because nuclio function restart fixes the problem. Thus, in case of network issue, we will wait forever and inform about this in the log
=> Move checks for errors

.github/workflows/ci.yaml, .github/workflows/golangci-lint.yml, .golangci.yml, Makefile, go.mod, hack/test/docker/Dockerfile, pkg/controlplane/http/session.go, pkg/controlplane/test/controlplane_test.go, pkg/dataplane/http/context.go, pkg/dataplane/itemscursor.go, pkg/dataplane/streamconsumergroup/claim.go, pkg/dataplane/streamconsumergroup/streamconsumergroup.go, pkg/dataplane/test/streamconsumergroup_test.go, pkg/dataplane/test/sync_test.go, pkg/dataplane/types.go, pkg/errors/errors.go
=> Bump go and linter to 1.23
